### ISSUE TITLE
key is missing?

### ISSUE THREAD

**Issue by dominictarr** [cabal-club/cabal-cli#162]
I tried running cabal-cli. I cloned the repo and ran `node cli.js --new`
it just output the usuage. looking in the code, I eventually figured out the particular usage print was inside

```
if (!cabalKeys.length) {
  console.log("key not provided") //i added this
  process.stderr.write(usage)
  process.exit(1)
} else {
```
it doesn't get to start because it checks this first, but I don't see anything about generating a key
reading the documentation I don't see any command for generating a key?

joining cabal cabal://0201400f1aa2e3076a3f17f4521b2cc41e258c446cdaa44742afe6e1b9fd5f82 did work.

**Comment by Raynos** [comment]
I tried running `cabal` with `cabal --new` and having a friend connect to the key it generated.

We were not able to talk to each other.

**Comment by noffle** [comment]
@dominictarr I was able to reproduce. Turns out this bug won't show if you already have some cabals in your `~/.cabal/v1/config.yml` -- I had to remove them first. I'll investigate when I get some time unless somebody else dives in. :)

@Raynos could you create a new issue for this? I don't think it's related to dominic's bug.

**Comment by noffle** [comment]
@dominictarr a workaround is to join an existing cabal, and then subsequent uses of `--new` should work
