### ISSUE TITLE
Moderation controls

### ISSUE THREAD

**Issue by garbados** [cabal-club/cabal-cli#41]
Users should have some control over the content they see:

- [ ] A user may set rules to mute keywords, optionally per user. Ex: `/mute [keyword] [username]`
- [ ] A user may mute another user, such as with a `/squelch` command.
- [ ] A user may mute another user and any mention of them, ex: `/shadowban [username]` such that it is functionally equivalent to `/mute [username]` and `/squelch [username]`
- [ ] A user may print their muting and squelching rules. Ex: `/rules`

Further, moderation controls should be stored as dat archives so that they can also be distributed. Consider:

- [ ] A user may print the discovery key of their muted keywords.
- [ ] A user may add keyword mutes by discovery key.
- [ ] A user may print the discovery key of their squelched usernames.
- [ ] A user may add squelched usernames by discovery key.

**Comment by garbados** [comment]
Further, moderation controls should be stored as dat archives so that they can also be distributed. Consider:

- [ ] A user may print the discovery key of their muted keywords.
- [ ] A user may add keyword mutes by discovery key.
- [ ] A user may print the discovery key of their squelched usernames.
- [ ] A user may add squelched usernames by discovery key.

**Comment by cblgh** [comment]
yes yes yes! this is a great issue, thankyou @garbados 🔥

**Comment by cblgh** [comment]
I was thinking a bit about this the other day and come up with a few subtleties that would be really nice wrt muting
- [ ] Mute user in a specified set of channels `/mute [username] [channel1 channel2 channel3]`
- [ ] Unmute a user in a specified set of channels `/unmute [username] [channel1 channel2 channel3]`

I guess it describes a kind of subjective [Access Control List](https://en.wikipedia.org/wiki/Access_control_list) for chatting

This allows for filtering your content in a way that doesn't impose restrictions on others. (Since channels act as a classifier for content.) If a person e.g. is great at technical topics, but spams a lot in the other channels then they can be muted globally and unmuted in the technical channels.

**Comment by noffle** [comment]
Client-side moderation would be a great fit for [cabal-client](https://github.com/cabal-club/cabal-client)!

**Comment by cblgh** [comment]
hey @garbados just wanted to say that this issue inspired & informed my master's thesis, which goes into the area of networks of trust for moderation. i'm on the last leg of the thesis and will probably be done by early spring this year!!

(also we've got some stuff already done on moderation in the core but we need to bubble it up to the clients https://github.com/cabal-club/cabal-core/#moderation)

**Comment by garbados** [comment]
I've seen the progress on this issue and I'm really pleased and impressed! Thanks for the followup. I look forward to reading your thesis!

**Comment by noffle** [comment]
Closing this for now, since we have the first version of moderation released, and other tracking issues around specific tasks.
